apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: zookeeper-prod

namespace: sre-demo

resources:
  - ../../base

# 生产环境配置
patches:
  # 生产环境使用5节点
  - target:
      kind: StatefulSet
      name: zk
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5

  # 增加资源限制
  - target:
      kind: StatefulSet
      name: zk
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi

# 镜像配置
images:
  - name: zookeeper
    newTag: 3.8.4